FROM registry.access.redhat.com/ubi8/openjdk-17:1.13-1
COPY animals-demo-1.0-SNAPSHOT-jar-with-dependencies.jar  /tmp
WORKDIR /tmp
CMD ["java", "-jar" , "animals-demo-1.0-SNAPSHOT-jar-with-dependencies.jar"]



