version: "2"
services:

  # Prometheus
  prom:
    container_name: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/config/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    user: "65534:0"
    volumes:
      - './config:/config'
      - './target/data/prometheus:/prometheus'

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.1.2-ubuntu
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_CONFIG=/config/grafana.ini
    user: "472:0"
    volumes:
      - './config:/config'
      - './target/data/grafana:/var/lib/grafana'
      - './target/logs/grafana:/var/log/grafana'

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55681:55681" # OTLP HTTP receiver alternative port
    depends_on:
      - jaeger-all-in-one
      - prom

  # Fish service
  fish-service:
    image: fish_demo:latest
    ports:
      - "8083:8083"
  # Mustelid service
  mustelid-service:
    image: mustelid_demo:latest
    ports:
      - "8084:8084"
  # Feline service
  feline-service:
    image: feline_demo:latest
    ports:
      - "8085:8085"
  # Mammal service
  mammal-service:
    image: mammal_demo:latest
    ports:
      - "8081:8081"
    depends_on:
      - feline-service
      - mustelid-service
  # Animal service
  animal-service:
    image: animals_demo:latest
    ports:
      - "8080:8080"
    depends_on:
      - fish-service
      - mammal-service
