receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
#    loglevel: debug

  jaeger:
    endpoint: 'jaeger-all-in-one:14250'
    insecure: true

  # Expect metrics like process.runtime.jvm.threads.count from OTel auto-instrument
  prometheus:
    endpoint: "otel-collector:7878"
    namespace: /animals-metrics
#    const_labels:
#      label1: value1
#      'another label': spaced value
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,prometheus]
